Flask manually captures exceptions, you will need to to call `capture_exception()` from the frameworks custom error handler to capture exceptions:

```python
from flask import Flask, jsonify
from posthog import Posthog

posthog = Posthog('<ph_project_api_key>', host='<ph_client_api_host>')

@app.errorhandler(Exception)
def handle_exception(e):
    posthog.capture_exception(e)
    response = jsonify({'message': str(e)})
    response.status_code = 500
    return response
```